export const SIGN_UP_USER = 'SIGN_UP_USER'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'
export const SIGN_IN_USER = 'SIGN_IN_USER'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERROR = 'CLEAR_ERROR'
